# Generated by Django 5.1.7 on 2025-03-20 08:38

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_course_learningoutcome"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="teacheruser",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="studentuser",
            name="average_score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="admin_user_set",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="admin_user_set",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="teacheruser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
